name: flutter_apps
publish_to: none
environment:
  sdk: ^3.11.4

dev_dependencies:
  melos: ^7.5.1
workspace:
  - packages/**
  - apps/**

melos:
  scripts:
    gen_exports:
      run: zsh scripts/gen_exports.sh {{args}}
      description: "lib配下のdartファイルを全てexportするbarrelファイルを自動生成 (パッケージ名を引数で指定)"
